### ISSUE TITLE
Expand README?

### ISSUE THREAD

**Issue by seenickcode** [newtriks/generator-env-config#2]
Hey thanks for writing this!

By the way, IMO it'd really help out the community I think (incl angular newbies like me) to point to an article on how to actually use the config files generated.  I couldn't find it in the README.  

Thanks in advance.

**Comment by newtriks** [comment]
Hey thanks for he feedback, check out this article I wrote:

http://newtriks.com/2013/11/29/environment-specific-configuration-in-angularjs-using-grunt/

**Comment by seenickcode** [comment]
Cool. 

I humbly recommend adding the link to the readme.

Thanks!

**Comment by newtriks** [comment]
It's been there all the time :) Top paragraph where I write: 

>  Example usage tutorial can be found [here](http://newtriks.com/2013/11/29/environment-specific-configuration-in-angularjs-using-grunt/).

**Comment by seenickcode** [comment]
Oops thanks!
